# ----------------------------
# Makefile Options
# ----------------------------

NAME = POTADBUG
ICON = icon.png
DESCRIPTION = "NicePotato's random debug"
COMPRESSED = NO
ARCHIVED = YES
HAS_PRINTF = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
