# ----------------------------
# Makefile Options
# ----------------------------

NAME = PHTMLLIB
ICON = icon.png
DESCRIPTION = "NicePotato's HTML lib"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
