# ----------------------------
# Makefile Options
# ----------------------------

NAME = HTMLTEST
ICON = icon.png
DESCRIPTION = "Test of PHTML"
COMPRESSED = NO
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz


# ----------------------------

include $(shell cedev-config --makefile)
